// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonCatcherGame.Server.Data;

#nullable disable

namespace PokemonCatcherGame.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes", (string)null);
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.Key", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DataProtected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsX509Certificate")
                        .HasColumnType("bit");

                    b.Property<string>("Use")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Use");

                    b.ToTable("Keys", (string)null);
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ConsumedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Key");

                    b.HasIndex("ConsumedTime");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.HasIndex("SubjectId", "SessionId", "Type");

                    b.ToTable("PersistedGrants", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PlayerItemInventoryEntityPokeBallEntity", b =>
                {
                    b.Property<int>("PlayerInventoryId")
                        .HasColumnType("int");

                    b.Property<int>("PokeBallsId")
                        .HasColumnType("int");

                    b.HasKey("PlayerInventoryId", "PokeBallsId");

                    b.HasIndex("PokeBallsId");

                    b.ToTable("PlayerItemInventoryEntityPokeBallEntity");
                });

            modelBuilder.Entity("PlayerItemInventoryEntityRejuvenationItemEntity", b =>
                {
                    b.Property<int>("PlayerInventoryId")
                        .HasColumnType("int");

                    b.Property<int>("ReviveItemsId")
                        .HasColumnType("int");

                    b.HasKey("PlayerInventoryId", "ReviveItemsId");

                    b.HasIndex("ReviveItemsId");

                    b.ToTable("PlayerItemInventoryEntityRejuvenationItemEntity");
                });

            modelBuilder.Entity("PlayerItemInventoryEntityStatusConditionItemEntity", b =>
                {
                    b.Property<int>("PlayerInventoryId")
                        .HasColumnType("int");

                    b.Property<int>("RemoveStatusConditionItemsId")
                        .HasColumnType("int");

                    b.HasKey("PlayerInventoryId", "RemoveStatusConditionItemsId");

                    b.HasIndex("RemoveStatusConditionItemsId");

                    b.ToTable("PlayerItemInventoryEntityStatusConditionItemEntity");
                });

            modelBuilder.Entity("PlayerItemInventoryEntityTechnicalMachineMoveEntity", b =>
                {
                    b.Property<int>("PlayerInventoryId")
                        .HasColumnType("int");

                    b.Property<int>("TMsId")
                        .HasColumnType("int");

                    b.HasKey("PlayerInventoryId", "TMsId");

                    b.HasIndex("TMsId");

                    b.ToTable("PlayerItemInventoryEntityTechnicalMachineMoveEntity");
                });

            modelBuilder.Entity("PokemonCatcherGame.Server.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Server.Entities.HealthItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AmountOfHealthRestored")
                        .HasColumnType("float");

                    b.Property<string>("HealthItemDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HealthItemName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PlayerItemInventoryEntityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerItemInventoryEntityId");

                    b.ToTable("HealthRestoratinItems");
                });

            modelBuilder.Entity("Server.Entities.PlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemIventoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ItemIventoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Server.Entities.PlayerItemInventoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameOfPlayer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlayerItemInventories");
                });

            modelBuilder.Entity("Server.Entities.PokeBallEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CatchRate")
                        .HasColumnType("float");

                    b.Property<string>("DescriptionOfPokeBall")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NameOfBall")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.HasKey("Id");

                    b.ToTable("PokeBalls");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            CatchRate = 0.25,
                            DescriptionOfPokeBall = "Used in battle : Attempts to catch a wild Pokémon, using a catch rate of 1x. If used in a trainer battle, nothing happens and the ball is lost.",
                            NameOfBall = "Poke Ball"
                        },
                        new
                        {
                            Id = 1002,
                            CatchRate = 0.5,
                            DescriptionOfPokeBall = "Used in battle : Attempts to catch a wild Pokémon, using a catch rate of 1.5x. If used in a trainer battle, nothing happens and the ball is lost.",
                            NameOfBall = "Great Ball"
                        },
                        new
                        {
                            Id = 1003,
                            CatchRate = 0.75,
                            DescriptionOfPokeBall = "Used in battle : Attempts to catch a wild Pokémon, using a catch rate of 2x. If used in a trainer battle, nothing happens and the ball is lost.",
                            NameOfBall = "Ultra Ball"
                        },
                        new
                        {
                            Id = 1004,
                            CatchRate = 100.0,
                            DescriptionOfPokeBall = "Used in battle : Catches a wild Pokémon without fail. If used in a trainer battle, nothing happens and the ball is lost.",
                            NameOfBall = "Master Ball"
                        },
                        new
                        {
                            Id = 1005,
                            CatchRate = 0.5,
                            DescriptionOfPokeBall = "Used in battle : Attempts to catch a wild Pokémon, using a catch rate of 1.5x. This item can only be used in the great marsh or kanto safari zone.",
                            NameOfBall = "Safari Ball"
                        },
                        new
                        {
                            Id = 1006,
                            CatchRate = 1.25,
                            DescriptionOfPokeBall = "Used in battle : Attempts to catch a wild Pokémon. If the wild Pokémon is water- or bug-type, this ball has a catch rate of 3x. Otherwise, it has a catch rate of 1x. If used in a trainer battle, nothing happens and the ball is lost.",
                            NameOfBall = "Net Ball"
                        },
                        new
                        {
                            Id = 1007,
                            CatchRate = 1.5,
                            DescriptionOfPokeBall = "Used in battle : Attempts to catch a wild Pokémon. If the wild Pokémon was encountered by surfing or fishing, this ball has a catch rate of 3.5x. Otherwise, it has a catch rate of 1x. If used in a trainer battle, nothing happens and the ball is lost.",
                            NameOfBall = "Dive Ball"
                        },
                        new
                        {
                            Id = 1008,
                            CatchRate = 1.8500000000000001,
                            DescriptionOfPokeBall = "Attempts to catch a wild Pokémon. Has a catch rate of given by `(40 - level) / 10`, where `level` is the wild Pokémon's level, to a maximum of 3.9xfor level 1 Pokémon. If the wild Pokémon's level is higher than 30, this ball has a catch rate of 1x.",
                            NameOfBall = "Nest Ball"
                        },
                        new
                        {
                            Id = 1009,
                            CatchRate = 1.25,
                            DescriptionOfPokeBall = "Used in battle : Attempts to catch a wild Pokémon. If the wild Pokémon's species is marked as caught in the trainer's Pokédex, this ball has a catch rate of 3x. Otherwise, it has a catch rate of 1x. If used in a trainer battle, nothing happens and the ball is lost.",
                            NameOfBall = "Repeat Ball"
                        },
                        new
                        {
                            Id = 1010,
                            CatchRate = 1.25,
                            DescriptionOfPokeBall = "Used in battle : Attempts to catch a wild Pokémon. Has a catch rate of 1.1x on the first turn of the battle and increases by 0.1x every turn, to a maximum of 4xon turn 30. If used in a trainer battle, nothing happens and the ball is lost.",
                            NameOfBall = "Timer ball"
                        },
                        new
                        {
                            Id = 1011,
                            CatchRate = 0.25,
                            DescriptionOfPokeBall = "Used in battle : Attempts to catch a wild Pokémon, using a catch rate of 1x. Whenever the caught Pokémon's happiness increases, it increases by one extra point. If used in a trainer battle, nothing happens and the ball is lost.",
                            NameOfBall = "Luxury Ball"
                        },
                        new
                        {
                            Id = 1012,
                            CatchRate = 0.25,
                            DescriptionOfPokeBall = "Used in battle : Attempts to catch a wild Pokémon, using a catch rate of 1×. If used in a trainer battle, nothing happens and the ball is lost.",
                            NameOfBall = "Premier Ball"
                        },
                        new
                        {
                            Id = 1013,
                            CatchRate = 1.5,
                            DescriptionOfPokeBall = "Used in battle : Attempts to catch a wild Pokémon. If it's currently nighttime or the wild Pokémon was encountered while walking in a cave, this ball has a catch rate of 3.5×. Otherwise, it has a catch rate of 1×. If used in a trainer battle, nothing happens and the ball is lost.",
                            NameOfBall = "Dusk Ball"
                        },
                        new
                        {
                            Id = 1014,
                            CatchRate = 0.25,
                            DescriptionOfPokeBall = "Used in battle : Attempts to catch a wild Pokémon, using a catch rate of 1×. The caught Pokémon's HP is immediately restored, PP for all its moves is restored, and any status ailment is cured. If used in a trainer battle, nothing happens and the ball is lost.",
                            NameOfBall = "Heal Ball"
                        },
                        new
                        {
                            Id = 1015,
                            CatchRate = 2.0,
                            DescriptionOfPokeBall = "Used in battle : Attempts to catch a wild Pokémon, using a catch rate of 4× on the first turn of a battle, but 1× any other time. If used in a trainer battle, nothing happens and the ball is lost.",
                            NameOfBall = "Quick Ball"
                        },
                        new
                        {
                            Id = 1016,
                            CatchRate = 0.25,
                            DescriptionOfPokeBall = "Used in battle : Attempts to catch a wild Pokémon, using a catch rate of 1×. If used in a trainer battle, nothing happens and the ball is lost.",
                            NameOfBall = "Cherish Ball"
                        });
                });

            modelBuilder.Entity("Server.Entities.PokemonAbilityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AbilityEffect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AbilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PokemonEntityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokemonEntityId");

                    b.ToTable("PokemonAbilities");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            AbilityEffect = "This Pokémon's damaging moves have a 10% chance to make the target flinch with each hit if they do not already cause flinching as a secondary effect. This ability does not stack with a held item. Overworld: The wild encounter rate is halved while this Pokémon is first in the party.",
                            AbilityName = "Stench"
                        },
                        new
                        {
                            Id = 1001,
                            AbilityEffect = "The weather changes to rain when this Pokémon enters battle and does not end unless replaced by another weather condition. If multiple Pokémon with this ability, drought, sand stream, or snow warning are sent out at the same time, the abilities will activate in order of Speed, respecting trick room. Each ability's weather will cancel the previous weather, and only the weather summoned by the slowest of the Pokémon will stay.",
                            AbilityName = "Drizzle"
                        },
                        new
                        {
                            Id = 1002,
                            AbilityEffect = "This Pokémon's Speed rises one stage after each turn.",
                            AbilityName = "Speed-Boost"
                        },
                        new
                        {
                            Id = 1003,
                            AbilityEffect = "This Pokémon's Speed rises one stage after each turn.",
                            AbilityName = "Battle-Armor"
                        },
                        new
                        {
                            Id = 1004,
                            AbilityEffect = "When this Pokémon is at full HP, any hit that would knock it out will instead leave it with 1 HP. Regardless of its current HP, it is also immune to the one-hit KO moves: fissure, guillotine, horn drill, and sheer cold. If this Pokémon is holding a focus sash, this ability takes precedence and the item will not be consumed.",
                            AbilityName = "Sturdy"
                        },
                        new
                        {
                            Id = 1005,
                            AbilityEffect = "While this Pokémon is in battle, self destruct and explosion will fail and aftermath will not take effect.",
                            AbilityName = "Damp"
                        },
                        new
                        {
                            Id = 1006,
                            AbilityEffect = "During a sandstorm, this Pokémon has 1.25xits evasion, and it does not take sandstorm damage regardless of type. The evasion bonus does not count as a stat modifier. Overworld: If the lead Pokémon has this ability, the wild encounter rate is halved in a sandstorm.",
                            AbilityName = "Sand-Veil"
                        },
                        new
                        {
                            Id = 1007,
                            AbilityEffect = "Whenever a move makes contact with this Pokémon, the move's user has a 30% chance of being paralyzed. Pokémon that are immune to electric-type moves can still be paralyzed by this ability. Overworld: If the lead Pokémon has this ability, there is a 50% chance that encounters will be with an electric Pokémon, if applicable.",
                            AbilityName = "Static"
                        },
                        new
                        {
                            Id = 1008,
                            AbilityEffect = "Whenever an electric-type move hits this Pokémon, it heals for 1/4 of its maximum HP, negating any other effect on it. This ability will not take effect if this Pokémon is ground-type and thus immune to Electric moves. Electric moves will ignore this Pokémon's substitute. This effect includes non-damaging moves, i.e. thunder wave.",
                            AbilityName = "Volt-Absorb"
                        },
                        new
                        {
                            Id = 1009,
                            AbilityEffect = "Whenever a water-type move hits this Pokémon, it heals for 1/4 of its maximum HP, negating any other effect on it. Water moves will ignore this Pokémon's substitute.",
                            AbilityName = "Water-Absorb"
                        },
                        new
                        {
                            Id = 1010,
                            AbilityEffect = "Whenever a water-type move hits this Pokémon, it heals for 1/4 of its maximum HP, negating any other effect on it. Water moves will ignore this Pokémon's substitute.",
                            AbilityName = "Water-Absorb"
                        },
                        new
                        {
                            Id = 1011,
                            AbilityEffect = "This Pokémon cannot be infatuated and is immune to captivate. If a Pokémon is infatuated and acquires this ability, its infatuation is cleared.",
                            AbilityName = "Oblivious"
                        },
                        new
                        {
                            Id = 1012,
                            AbilityEffect = "This Pokémon's moves have 1.3xtheir accuracy. This ability has no effect on the one-hit KO moves (fissure, guillotine, horn drill, and sheer cold). Overworld: If the first Pokémon in the party has this ability, the chance of a wild Pokémon holding a particular item is raised from 50%, 5%, or 1% to 60%, 20%, or 5%, respectively.",
                            AbilityName = "Compound-Eyes"
                        },
                        new
                        {
                            Id = 1013,
                            AbilityEffect = "This Pokémon cannot be asleep. This causes rest to fail altogether. If a Pokémon is asleep and acquires this ability, it will immediately wake up; this includes when regaining a lost ability upon leaving battle. This ability functions identically to vital spirit in battle.",
                            AbilityName = "Insomnia"
                        },
                        new
                        {
                            Id = 1014,
                            AbilityEffect = "Whenever this Pokémon takes damage from a move, the Pokémon's type changes to match the move. If the Pokémon has two types, both are overridden. The Pokémon must directly take damage; for example, moves blocked by a substitute will not trigger this ability, nor will moves that deal damage indirectly, such as spikes. This ability takes effect on only the last hit of a multiple-hit attack.",
                            AbilityName = "Color-Change"
                        },
                        new
                        {
                            Id = 1015,
                            AbilityEffect = "This Pokémon cannot be poisoned. This includes bad poison. If a Pokémon is poisoned and acquires this ability, its poison is healed; this includes when regaining a lost ability upon leaving battle.",
                            AbilityName = "Immunity"
                        },
                        new
                        {
                            Id = 1016,
                            AbilityEffect = "This Pokémon is immune to fire-type moves. Once this Pokémon has been hit by a Fire move, its own Fire moves will inflict 1.5xas much damage until it leaves battle. This ability has no effect while the Pokémon is frozen. The Fire damage bonus is retained even if the Pokémon is frozen and thawed or the ability is lost or disabled. Fire moves will ignore this Pokémon's substitute. This ability takes effect even on non-damaging moves, i.e. will o wisp.",
                            AbilityName = "Flash-Fire"
                        },
                        new
                        {
                            Id = 1017,
                            AbilityEffect = "This Pokémon cannot be confused. If a Pokémon is confused and acquires this ability, its confusion will immediately be healed.",
                            AbilityName = "Own-Tempo"
                        },
                        new
                        {
                            Id = 1018,
                            AbilityEffect = "When this Pokémon enters battle, the opponent's Attack is lowered by one stage. In a double battle, both opponents are affected. This ability also takes effect when acquired during a battle, but will not take effect again if lost and reobtained without leaving battle. This ability has no effect on an opponent that has a substitute. Overworld: If the first Pokémon in the party has this ability, any random encounter with a Pokémon five or more levels lower than it has a 50% chance of being skipped.",
                            AbilityName = "Intimidate"
                        },
                        new
                        {
                            Id = 1019,
                            AbilityEffect = "Whenever a move makes contact with this Pokémon, the move's user takes 1/8 of its maximum HP in damage. This ability functions identically to iron barbs.",
                            AbilityName = "Rough-Skin"
                        },
                        new
                        {
                            Id = 1020,
                            AbilityEffect = "This Pokémon is immune to ground-type moves, spikes, toxic spikes, and arena trap. This ability is disabled during gravity or ingrain, or while holding an iron ball. This ability is not disabled during roost.",
                            AbilityName = "Levitate"
                        },
                        new
                        {
                            Id = 1021,
                            AbilityEffect = "Whenever a move makes contact with this Pokémon, the move's user has a 30% chance of being paralyzed, poisoned, or put to sleep, chosen at random. Nothing is done to compensate if the move's user is immune to one of these ailments; there is simply a lower chance that the move's user will be affected.",
                            AbilityName = "Effect-Spore"
                        },
                        new
                        {
                            Id = 1022,
                            AbilityEffect = "Whenever this Pokémon is burned, paralyzed, or poisoned, the Pokémon who gave this Pokémon that ailment is also given the ailment. This ability passes back bad poison when this Pokémon is badly poisoned. This ability cannot pass on a status ailment that the Pokémon did not directly receive from another Pokémon, such as the poison from toxic spikes or the burn from a flame orb. Overworld: If the lead Pokémon has this ability, wild Pokémon have a 50% chance of having the lead Pokémon's nature, and a 50% chance of being given a random nature as usual, including the lead Pokémon's nature. This does not work on Pokémon received outside of battle or roaming legendaries.",
                            AbilityName = "Synchronize"
                        },
                        new
                        {
                            Id = 1023,
                            AbilityEffect = "This Pokémon is cured of any major status ailment when it is switched out for another Pokémon. If this ability is acquired during battle, the Pokémon is cured upon leaving battle before losing the temporary ability.",
                            AbilityName = "Natural-Cure"
                        },
                        new
                        {
                            Id = 1024,
                            AbilityEffect = "This Pokémon's Speed is doubled during strong sunlight. This bonus does not count as a stat modifier.",
                            AbilityName = "Chlorophyll"
                        },
                        new
                        {
                            Id = 1025,
                            AbilityEffect = "When this Pokémon enters battle, it copies a random opponent's ability. This ability cannot copy flower gift, forecast, illusion, imposter, multitype, trace, wonder guard, or zen mode.",
                            AbilityName = "Trace"
                        },
                        new
                        {
                            Id = 1026,
                            AbilityEffect = "This Pokémon's Attack is doubled while in battle. This bonus does not count as a stat modifier. This ability functions identically to pure power.",
                            AbilityName = "Huge-Power"
                        },
                        new
                        {
                            Id = 1027,
                            AbilityEffect = "Whenever a move makes contact with this Pokémon, the move's user has a 30% chance of being poisoned.",
                            AbilityName = "Poison-Point"
                        },
                        new
                        {
                            Id = 1028,
                            AbilityEffect = "This Pokémon cannot flinch.",
                            AbilityName = "Inner-Focus"
                        },
                        new
                        {
                            Id = 1029,
                            AbilityEffect = "This Pokémon cannot be frozen. If a Pokémon is frozen and acquires this ability, it will immediately thaw out; this includes when regaining a lost ability upon leaving battle. Overworld: If any Pokémon in the party has this ability, each egg in the party has its hatch counter decreased by 2 (rather than 1) each step cycle, making eggs hatch roughly twice as quickly. This effect does not stack if multiple Pokémon have this ability or flame body.",
                            AbilityName = "Magma-Armor"
                        },
                        new
                        {
                            Id = 1030,
                            AbilityEffect = "This Pokémon cannot be burned. If a Pokémon is burned and acquires this ability, its burn is healed; this includes when regaining a lost ability upon leaving battle.",
                            AbilityName = "Water-Veil"
                        },
                        new
                        {
                            Id = 1031,
                            AbilityEffect = "This Pokémon heals for 1/16 of its maximum HP after each turn during rain.",
                            AbilityName = "Rain-Dish"
                        },
                        new
                        {
                            Id = 1032,
                            AbilityEffect = "Moves targetting this Pokémon use one extra PP. This ability stacks if multiple targets have it. This ability still affects moves that fail or miss. This ability does not affect ally moves that target either the entire field or just its side, nor this Pokémon's self-targetted moves; it does, however, affect single-targetted ally moves aimed at this Pokémon, ally moves that target all other Pokémon, and opponents' moves that target the entire field. If this ability raises a move's PP cost above its remaining PP, it will use all remaining PP. When this Pokémon enters battle, all participating trainers are notified that it has this ability. Overworld: If the lead Pokémon has this ability, higher-levelled Pokémon have their encounter rate increased.",
                            AbilityName = "Pressure"
                        },
                        new
                        {
                            Id = 1033,
                            AbilityEffect = "Whenever a move makes contact with this Pokémon, the move's user has a 30% chance of being burned. Overworld: If any Pokémon in the party has this ability, each egg in the party has its hatch counter decreased by 2 (rather than 1) each step cycle, making eggs hatch roughly twice as quickly. This effect does not stack if multiple Pokémon have this ability or magma armor.",
                            AbilityName = "Flame-Body"
                        },
                        new
                        {
                            Id = 1034,
                            AbilityEffect = "This Pokémon cannot have its accuracy lowered. This ability does not prevent any accuracy losses other than stat modifiers, such as the accuracy cut from fog; nor does it prevent other Pokémon's evasion from making this Pokémon's moves less accurate. This Pokémon can still be passed negative accuracy modifiers through heart swap. Overworld: If the first Pokémon in the party has this ability, any random encounter with a Pokémon five or more levels lower than it has a 50% chance of being skipped.",
                            AbilityName = "Keen-Eye"
                        },
                        new
                        {
                            Id = 1035,
                            AbilityEffect = "Every second turn on which this Pokémon should attempt to use a move, it will instead do nothing (loaf around). Loafing around interrupts moves that take multiple turns the same way paralysis, flinching, etc do. Most such moves, for example bide or rollout, are simply cut off upon loafing around. Attacks with a recharge turn, such as hyper beam, do not have to recharge; attacks with a preparation turn, such as fly, do not end up being used. Moves that are forced over multiple turns and keep going through failure, such as outrage, uproar, or any move forced by encore, keep going as usual. If this Pokémon is confused, its confusion is not checked when loafing around; the Pokémon cannot hurt itself, and its confusion does not end or come closer to ending. If this Pokémon attempts to move but fails, e.g. because of paralysis or gravity, it still counts as having moved and will loaf around the next turn. If it does not attempt to move, e.g. because it is asleep or frozen, whatever it would have done will be postponed until its next attempt; that is, it will either loaf around or move as usual, depending on what it last did. This ability cannot be changed with worry seed, but it can be disabled with gastro acid, changed with role play, or traded away with skill swap.",
                            AbilityName = "Truant"
                        },
                        new
                        {
                            Id = 1036,
                            AbilityEffect = "After each turn, this Pokémon has a 33% of being cured of any major status ailment.",
                            AbilityName = "Shed-Skin"
                        },
                        new
                        {
                            Id = 1037,
                            AbilityEffect = "Whenever a Pokémon would heal after hitting this Pokémon with a leeching move like absorb, it instead loses as many HP as it would usually gain. dream eater is unaffected.",
                            AbilityName = "Liquid-Ooze"
                        },
                        new
                        {
                            Id = 1038,
                            AbilityEffect = "Whenever a Pokémon would heal after hitting this Pokémon with a leeching move like absorb, it instead loses as many HP as it would usually gain. dream eater is unaffected.",
                            AbilityName = "Liquid-Ooze"
                        });
                });

            modelBuilder.Entity("Server.Entities.PokemonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseExperience")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int?>("MoveFourId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("MoveOneId")
                        .HasColumnType("int");

                    b.Property<int>("MoveThreeId")
                        .HasColumnType("int");

                    b.Property<int>("MoveTwoId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayerEntityId")
                        .HasColumnType("int");

                    b.Property<int>("PokeTypeIdOne")
                        .HasColumnType("int");

                    b.Property<int?>("PokeTypeIdTwo")
                        .HasColumnType("int");

                    b.Property<int>("PokedexNumber")
                        .HasColumnType("int");

                    b.Property<int?>("TrainerOpponentEntityId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MoveFourId");

                    b.HasIndex("MoveOneId");

                    b.HasIndex("MoveThreeId");

                    b.HasIndex("MoveTwoId");

                    b.HasIndex("PlayerEntityId");

                    b.HasIndex("PokeTypeIdOne");

                    b.HasIndex("PokeTypeIdTwo");

                    b.HasIndex("TrainerOpponentEntityId");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("Server.Entities.PokemonMoveEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Accuracy")
                        .HasColumnType("int");

                    b.Property<int>("HealthRestorationAmount")
                        .HasColumnType("int");

                    b.Property<bool>("MoveAppliesAStatusCondition")
                        .HasColumnType("bit");

                    b.Property<int>("MoveBasePP")
                        .HasColumnType("int");

                    b.Property<string>("MoveDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MoveName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovePower")
                        .HasColumnType("int");

                    b.Property<bool>("MoveRestoresHealth")
                        .HasColumnType("bit");

                    b.Property<string>("MoveType")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<int?>("PokemonEntityId")
                        .HasColumnType("int");

                    b.Property<int?>("StatusConditionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokemonEntityId");

                    b.HasIndex("StatusConditionId");

                    b.ToTable("PokemonMoves");
                });

            modelBuilder.Entity("Server.Entities.PokemonTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PokeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PokemonTypes");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            PokeType = "Normal"
                        },
                        new
                        {
                            Id = 1001,
                            PokeType = "Fighting"
                        },
                        new
                        {
                            Id = 1002,
                            PokeType = "Flying"
                        },
                        new
                        {
                            Id = 1003,
                            PokeType = "Poison"
                        },
                        new
                        {
                            Id = 1004,
                            PokeType = "Ground"
                        },
                        new
                        {
                            Id = 1005,
                            PokeType = "Rock"
                        },
                        new
                        {
                            Id = 1006,
                            PokeType = "Bug"
                        },
                        new
                        {
                            Id = 1007,
                            PokeType = "Ghost"
                        },
                        new
                        {
                            Id = 1008,
                            PokeType = "Steel"
                        },
                        new
                        {
                            Id = 1009,
                            PokeType = "Fire"
                        },
                        new
                        {
                            Id = 1010,
                            PokeType = "Water"
                        },
                        new
                        {
                            Id = 1011,
                            PokeType = "Grass"
                        },
                        new
                        {
                            Id = 1012,
                            PokeType = "Electric"
                        },
                        new
                        {
                            Id = 1013,
                            PokeType = "Psychic"
                        },
                        new
                        {
                            Id = 1014,
                            PokeType = "Ice"
                        },
                        new
                        {
                            Id = 1015,
                            PokeType = "Dragon"
                        },
                        new
                        {
                            Id = 1016,
                            PokeType = "Dark"
                        },
                        new
                        {
                            Id = 1017,
                            PokeType = "Fairy"
                        });
                });

            modelBuilder.Entity("Server.Entities.RejuvenationItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RejuvenationItemDescription")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("RejuvenationItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("ReviveHealthAmount")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ReviveItems");
                });

            modelBuilder.Entity("Server.Entities.StatusConditionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BurnEffect")
                        .HasColumnType("bit");

                    b.Property<bool>("ConditionDoesDamage")
                        .HasColumnType("bit");

                    b.Property<string>("ConditionDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DamageAmount")
                        .HasColumnType("float");

                    b.Property<string>("DamageFrequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FreezeEffect")
                        .HasColumnType("bit");

                    b.Property<bool>("ParalysisEffect")
                        .HasColumnType("bit");

                    b.Property<bool>("PoisonEffect")
                        .HasColumnType("bit");

                    b.Property<bool>("SleepEffect")
                        .HasColumnType("bit");

                    b.Property<string>("StatusConditionDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("StatusConditionName")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.HasKey("Id");

                    b.ToTable("StatusConditions");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            BurnEffect = false,
                            ConditionDoesDamage = false,
                            ConditionDuration = "The affect lasts four turns, unless it is removed by an item.",
                            DamageAmount = 0.0,
                            DamageFrequency = "Last for four turns.",
                            FreezeEffect = false,
                            ParalysisEffect = true,
                            PoisonEffect = false,
                            SleepEffect = false,
                            StatusConditionDescription = "The Pokémon afflicted Speed stat is reduced to 50% of it's maximum. The Pokémon has a 25% chance of being unable to attack each turn",
                            StatusConditionName = "Paralysis"
                        },
                        new
                        {
                            Id = 1002,
                            BurnEffect = true,
                            ConditionDoesDamage = true,
                            ConditionDuration = "Last until healed or pokemon faints.",
                            DamageAmount = 15.0,
                            DamageFrequency = "Last until healed or pokemon faints.",
                            FreezeEffect = false,
                            ParalysisEffect = false,
                            PoisonEffect = false,
                            SleepEffect = false,
                            StatusConditionDescription = "The pokemon is afflicted with a severe burn. Each turn, the Pokémon afflicted with the Burn loses 1/8th of it's Max HP.",
                            StatusConditionName = "Burn"
                        },
                        new
                        {
                            Id = 1003,
                            BurnEffect = false,
                            ConditionDoesDamage = false,
                            ConditionDuration = "The affect lasts four turns, unless it is removed by an item.",
                            DamageAmount = 0.0,
                            DamageFrequency = "Last for four turns.",
                            FreezeEffect = true,
                            ParalysisEffect = false,
                            PoisonEffect = false,
                            SleepEffect = false,
                            StatusConditionDescription = "The Pokemon is frozen solid. The Pokémon cannot use any attacks (apart from those that thaw it)",
                            StatusConditionName = "Freeze "
                        },
                        new
                        {
                            Id = 1004,
                            BurnEffect = false,
                            ConditionDoesDamage = true,
                            ConditionDuration = "Last until the Pokemon is healed or the Pokemon Faints.",
                            DamageAmount = 15.0,
                            DamageFrequency = "Last until the Pokemon is healed or the Pokemon Faints.",
                            FreezeEffect = false,
                            ParalysisEffect = false,
                            PoisonEffect = true,
                            SleepEffect = false,
                            StatusConditionDescription = "Poisons the targeted pokemon gradually lowering the Pokémon's Hit Points until the Pokémon faint.",
                            StatusConditionName = "Poison"
                        },
                        new
                        {
                            Id = 1005,
                            BurnEffect = false,
                            ConditionDoesDamage = false,
                            ConditionDuration = "Last for up to seven turns unless removed.",
                            DamageAmount = 0.0,
                            DamageFrequency = "Last for up to seven turns unless removed.",
                            FreezeEffect = false,
                            ParalysisEffect = false,
                            PoisonEffect = false,
                            SleepEffect = true,
                            StatusConditionDescription = "The targeted Pokemon is put to sleep for up to seven turns. The pokemon is not able to use any moves while asleep.",
                            StatusConditionName = "Sleep"
                        });
                });

            modelBuilder.Entity("Server.Entities.StatusConditionItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("RemovesBurn")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovesFreeze")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovesParalysis")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovesPoison")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovesSleep")
                        .HasColumnType("bit");

                    b.Property<string>("StatusConditionItemDescription")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("StatusConditionItemName")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)");

                    b.HasKey("Id");

                    b.ToTable("StatusConditionItems");
                });

            modelBuilder.Entity("Server.Entities.TechnicalMachineMoveEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BugCanLearn")
                        .HasColumnType("bit");

                    b.Property<bool>("DarkCanLearn")
                        .HasColumnType("bit");

                    b.Property<bool>("DragonCanLearn")
                        .HasColumnType("bit");

                    b.Property<bool>("ElectricCanLearn")
                        .HasColumnType("bit");

                    b.Property<bool>("FairyCanLearn")
                        .HasColumnType("bit");

                    b.Property<bool>("FightingCanLearn")
                        .HasColumnType("bit");

                    b.Property<bool>("FireCanLearn")
                        .HasColumnType("bit");

                    b.Property<bool>("GhostCanLearn")
                        .HasColumnType("bit");

                    b.Property<bool>("GrassCanLearn")
                        .HasColumnType("bit");

                    b.Property<bool>("GroundCanLearn")
                        .HasColumnType("bit");

                    b.Property<int>("HealthRestorationAmount")
                        .HasColumnType("int");

                    b.Property<bool>("IceCanLearn")
                        .HasColumnType("bit");

                    b.Property<bool>("MoveAppliesAStatusCondition")
                        .HasColumnType("bit");

                    b.Property<int>("MoveBasePP")
                        .HasColumnType("int");

                    b.Property<string>("MoveDescription")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("MoveName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int>("MovePower")
                        .HasColumnType("int");

                    b.Property<bool>("MoveRestoresHealth")
                        .HasColumnType("bit");

                    b.Property<string>("MoveType")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<bool>("NormalCanLearn")
                        .HasColumnType("bit");

                    b.Property<bool>("PoisonCanLearn")
                        .HasColumnType("bit");

                    b.Property<int?>("PokemonEntityId")
                        .HasColumnType("int");

                    b.Property<bool>("PsychicCanLearn")
                        .HasColumnType("bit");

                    b.Property<bool>("RockCanLearn")
                        .HasColumnType("bit");

                    b.Property<int>("StatusConditionId")
                        .HasColumnType("int");

                    b.Property<bool>("SteelCanLearn")
                        .HasColumnType("bit");

                    b.Property<bool>("WaterCanLearn")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PokemonEntityId");

                    b.HasIndex("StatusConditionId");

                    b.ToTable("TMs");
                });

            modelBuilder.Entity("Server.Entities.TrainerOpponentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OpponentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Opponents");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PokemonCatcherGame.Server.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PokemonCatcherGame.Server.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonCatcherGame.Server.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PokemonCatcherGame.Server.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayerItemInventoryEntityPokeBallEntity", b =>
                {
                    b.HasOne("Server.Entities.PlayerItemInventoryEntity", null)
                        .WithMany()
                        .HasForeignKey("PlayerInventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Entities.PokeBallEntity", null)
                        .WithMany()
                        .HasForeignKey("PokeBallsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayerItemInventoryEntityRejuvenationItemEntity", b =>
                {
                    b.HasOne("Server.Entities.PlayerItemInventoryEntity", null)
                        .WithMany()
                        .HasForeignKey("PlayerInventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Entities.RejuvenationItemEntity", null)
                        .WithMany()
                        .HasForeignKey("ReviveItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayerItemInventoryEntityStatusConditionItemEntity", b =>
                {
                    b.HasOne("Server.Entities.PlayerItemInventoryEntity", null)
                        .WithMany()
                        .HasForeignKey("PlayerInventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Entities.StatusConditionItemEntity", null)
                        .WithMany()
                        .HasForeignKey("RemoveStatusConditionItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayerItemInventoryEntityTechnicalMachineMoveEntity", b =>
                {
                    b.HasOne("Server.Entities.PlayerItemInventoryEntity", null)
                        .WithMany()
                        .HasForeignKey("PlayerInventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Entities.TechnicalMachineMoveEntity", null)
                        .WithMany()
                        .HasForeignKey("TMsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Entities.HealthItemEntity", b =>
                {
                    b.HasOne("Server.Entities.PlayerItemInventoryEntity", null)
                        .WithMany("HealthItems")
                        .HasForeignKey("PlayerItemInventoryEntityId");
                });

            modelBuilder.Entity("Server.Entities.PlayerEntity", b =>
                {
                    b.HasOne("Server.Entities.PlayerItemInventoryEntity", "ItemInventory")
                        .WithMany()
                        .HasForeignKey("ItemIventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonCatcherGame.Server.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemInventory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Entities.PokemonAbilityEntity", b =>
                {
                    b.HasOne("Server.Entities.PokemonEntity", null)
                        .WithMany("AbilitiesList")
                        .HasForeignKey("PokemonEntityId");
                });

            modelBuilder.Entity("Server.Entities.PokemonEntity", b =>
                {
                    b.HasOne("Server.Entities.PokemonMoveEntity", "MoveFour")
                        .WithMany()
                        .HasForeignKey("MoveFourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Entities.PokemonMoveEntity", "MoveOne")
                        .WithMany()
                        .HasForeignKey("MoveOneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Entities.PokemonMoveEntity", "MoveThree")
                        .WithMany()
                        .HasForeignKey("MoveThreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Entities.PokemonMoveEntity", "MoveTwo")
                        .WithMany()
                        .HasForeignKey("MoveTwoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Entities.PlayerEntity", null)
                        .WithMany("CaughtPokemon")
                        .HasForeignKey("PlayerEntityId");

                    b.HasOne("Server.Entities.PokemonTypeEntity", "PokeTypeOne")
                        .WithMany()
                        .HasForeignKey("PokeTypeIdOne")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Entities.PokemonTypeEntity", "PokeTypeTwo")
                        .WithMany()
                        .HasForeignKey("PokeTypeIdTwo");

                    b.HasOne("Server.Entities.TrainerOpponentEntity", null)
                        .WithMany("UsablePokemon")
                        .HasForeignKey("TrainerOpponentEntityId");

                    b.Navigation("MoveFour");

                    b.Navigation("MoveOne");

                    b.Navigation("MoveThree");

                    b.Navigation("MoveTwo");

                    b.Navigation("PokeTypeOne");

                    b.Navigation("PokeTypeTwo");
                });

            modelBuilder.Entity("Server.Entities.PokemonMoveEntity", b =>
                {
                    b.HasOne("Server.Entities.PokemonEntity", null)
                        .WithMany("Moves")
                        .HasForeignKey("PokemonEntityId");

                    b.HasOne("Server.Entities.StatusConditionEntity", "StatusCondition")
                        .WithMany()
                        .HasForeignKey("StatusConditionId");

                    b.Navigation("StatusCondition");
                });

            modelBuilder.Entity("Server.Entities.TechnicalMachineMoveEntity", b =>
                {
                    b.HasOne("Server.Entities.PokemonEntity", null)
                        .WithMany("TeachableMoves")
                        .HasForeignKey("PokemonEntityId");

                    b.HasOne("Server.Entities.StatusConditionEntity", "StatusCondition")
                        .WithMany()
                        .HasForeignKey("StatusConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusCondition");
                });

            modelBuilder.Entity("Server.Entities.PlayerEntity", b =>
                {
                    b.Navigation("CaughtPokemon");
                });

            modelBuilder.Entity("Server.Entities.PlayerItemInventoryEntity", b =>
                {
                    b.Navigation("HealthItems");
                });

            modelBuilder.Entity("Server.Entities.PokemonEntity", b =>
                {
                    b.Navigation("AbilitiesList");

                    b.Navigation("Moves");

                    b.Navigation("TeachableMoves");
                });

            modelBuilder.Entity("Server.Entities.TrainerOpponentEntity", b =>
                {
                    b.Navigation("UsablePokemon");
                });
#pragma warning restore 612, 618
        }
    }
}
